//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facultyyyyyy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userr
    {
        public int id { get; set; }
        public string namee { get; set; }
        public string gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Addresss { get; set; }
        public string Department { get; set; }
    }
}
